name: PHPUnit Tests

on:
  - push
  - pull_request

jobs:
  phpunit:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php: [7.4, 8.0, 8.1, 8.2]
        laravel: ['9.*', '10.*', '11.*']
        stability: [prefer-lowest, prefer-stable]
        exclude:
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0
          - laravel: 11.*
            php: 7.4
          - laravel: 11.*
            php: 8.0
          - laravel: 11.*
            php: 8.1

    name: PHP ${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability}}


    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov


      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist --${{ matrix.stability }}


      - name: Run phpunit
        run: vendor/bin/phpunit --coverage-clover build/logs/clover.xml -v


      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL: true
          COVERALLS_FLAG_NAME: php-${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability}}
        run: vendor/bin/php-coveralls --coverage_clover=build/logs/clover.xml -vvv

  finish-coverage:
    needs: phpunit

    runs-on: ubuntu-latest


    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
